chore: Use regexp instead of glob
```
Error: SyntaxError: Invalid regular expression: /**/chore-/: Nothing to repeat
Error: Invalid regular expression: /**/chore-/: Nothing to repeat
```